services:
  backend:
    image: api_v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001"
    env_file:
      - .env
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 900M
        reservations:
          cpus: '0.5'
          memory: 250M
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3001/health" ]
      interval: 13s
      timeout: 10s
      retries: 3
    networks:
      - app-cenfi

  nginx:
    image: nginx:alpine
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 250M
    networks:
      - app-cenfi

networks:
  app-cenfi:
    name: app-cenfi
    driver: bridge
