###
### POST question
POST http://localhost:3001/api/v1/questions
Content-Type: application/json

{
    "statement": "¿Cuánto es 10 + 1?",
    "answer": 3,
    "imageName": "https://example.com/uploads/image.jpg",
    "justification": "Porque si"
}
###

### Listar preguntas todas las preguntas
GET http://localhost:3001/api/v1/questions?page=1&count=5
Content-Type: application/json
###

###
### Obtener una preguntas por ID
GET http://localhost:3001/api/v1/questions/81
Content-Type: application/json
