name: Build and Lift with Docker Compose

on:
  pull_request:
    branches:
      - releasev1

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/cenfi-app/api-cenfi
            touch testFile.txt
            git fetch --depth=1
            git reset --hard origin/main
            echo "Tearing down Docker Compose containers..."
            docker compose down || true
            echo "Starting Docker Compose containers with rebuild..."
            docker compose up --build -d
            exit
